/*
 * Copyright (c) 2026 by Naohide Sano, All rights reserved.
 *
 * Programmed by Naohide Sano
 */

package vavi.nio.file.cyberduck;

import java.io.IOException;
import java.net.URI;
import java.nio.file.Files;
import java.nio.file.Path;
import java.security.Principal;
import java.util.Comparator;
import java.util.List;
import java.util.stream.Stream;

import org.apache.catalina.Context;
import org.apache.catalina.LifecycleException;
import org.apache.catalina.Wrapper;
import org.apache.catalina.authenticator.BasicAuthenticator;
import org.apache.catalina.connector.Connector;
import org.apache.catalina.realm.GenericPrincipal;
import org.apache.catalina.realm.RealmBase;
import org.apache.catalina.servlets.WebdavServlet;
import org.apache.catalina.startup.Tomcat;
import org.apache.tomcat.util.descriptor.web.LoginConfig;
import org.apache.tomcat.util.descriptor.web.SecurityCollection;
import org.apache.tomcat.util.descriptor.web.SecurityConstraint;
import org.apache.tomcat.util.net.SSLHostConfig;
import org.apache.tomcat.util.net.SSLHostConfigCertificate;


/**
 * A temporary webdav server (https, basic authentication) for tests.
 * <p>
 * Embedded tomcat's {@link WebdavServlet} serves a temporary directory.
 * A self-signed certificate is generated by keytool for each server.
 * </p>
 *
 * @author <a href="mailto:umjammer@gmail.com">Naohide Sano</a> (nsano)
 * @version 0.00 2026-10-08 nsano initial version <br>
 */
class WebdavTestServer implements AutoCloseable {

    static final String USER = "tester";
    static final String PASSWORD = "testpassword";
    private static final String ROLE = "dav";
    private static final String STORE_PASSWORD = "changeit";

    private final Path base;
    private final Path root;
    private final Tomcat tomcat;
    private final Connector connector;

    /** a realm for the only one user */
    private static final class SingleUserRealm extends RealmBase {

        @Override
        protected String getPassword(String username) {
            return USER.equals(username) ? PASSWORD : null;
        }

        @Override
        protected Principal getPrincipal(String username) {
            return USER.equals(username) ? new GenericPrincipal(username, List.of(ROLE)) : null;
        }
    }

    WebdavTestServer() throws IOException, InterruptedException, LifecycleException {
        base = Files.createTempDirectory("webdav-test-");
        root = Files.createDirectory(base.resolve("root"));
        Path keyStore = createKeyStore(base.resolve("keystore.p12"));

        tomcat = new Tomcat();
        tomcat.setBaseDir(base.resolve("tomcat").toString());

        connector = new Connector("org.apache.coyote.http11.Http11NioProtocol");
        connector.setPort(0);
        connector.setProperty("address", "127.0.0.1");
        connector.setScheme("https");
        connector.setSecure(true);
        connector.setProperty("SSLEnabled", "true");
        SSLHostConfig sslHostConfig = new SSLHostConfig();
        SSLHostConfigCertificate certificate = new SSLHostConfigCertificate(sslHostConfig, SSLHostConfigCertificate.Type.RSA);
        certificate.setCertificateKeystoreFile(keyStore.toString());
        certificate.setCertificateKeystorePassword(STORE_PASSWORD);
        certificate.setCertificateKeystoreType("PKCS12");
        sslHostConfig.addCertificate(certificate);
        connector.addSslHostConfig(sslHostConfig);
        tomcat.getService().addConnector(connector);
        tomcat.setConnector(connector);

        Context context = tomcat.addContext("", root.toString());

        Wrapper servlet = Tomcat.addServlet(context, "webdav", new WebdavServlet());
        servlet.addInitParameter("readonly", "false");
        servlet.addInitParameter("listings", "true");
        context.addServletMappingDecoded("/*", "webdav");

        context.setRealm(new SingleUserRealm());
        LoginConfig loginConfig = new LoginConfig();
        loginConfig.setAuthMethod("BASIC");
        loginConfig.setRealmName("test");
        context.setLoginConfig(loginConfig);
        context.getPipeline().addValve(new BasicAuthenticator());
        SecurityCollection collection = new SecurityCollection();
        collection.addPattern("/*");
        SecurityConstraint constraint = new SecurityConstraint();
        constraint.addAuthRole(ROLE);
        constraint.addCollection(collection);
        context.addConstraint(constraint);
        context.addSecurityRole(ROLE);

        tomcat.start();
    }

    /** creates a self-signed certificate for localhost */
    private static Path createKeyStore(Path keyStore) throws IOException, InterruptedException {
        Path keytool = Path.of(System.getProperty("java.home"), "bin", "keytool");
        Process process = new ProcessBuilder(keytool.toString(),
                "-genkeypair", "-alias", "tomcat", "-keyalg", "RSA", "-keysize", "2048", "-validity", "2",
                "-dname", "CN=localhost", "-ext", "SAN=dns:localhost,ip:127.0.0.1",
                "-storetype", "PKCS12", "-keystore", keyStore.toString(),
                "-storepass", STORE_PASSWORD, "-keypass", STORE_PASSWORD)
                .redirectErrorStream(true)
                .start();
        String output = new String(process.getInputStream().readAllBytes());
        if (process.waitFor() != 0) {
            throw new IOException("keytool failed: " + output);
        }
        return keyStore;
    }

    /** the directory served as "/" */
    Path getRoot() {
        return root;
    }

    /** @return "cyberduck:webdav://..." uri for this server */
    URI getUri() {
        return URI.create(String.format("cyberduck:webdav://%s:%s@localhost:%d/", USER, PASSWORD, connector.getLocalPort()));
    }

    @Override
    public void close() throws IOException {
        try {
            tomcat.stop();
            tomcat.destroy();
        } catch (LifecycleException e) {
            throw new IOException(e);
        } finally {
            try (Stream<Path> s = Files.walk(base)) {
                s.sorted(Comparator.reverseOrder()).forEach(p -> p.toFile().delete());
            }
        }
    }
}
