# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      env:
        TEST_WEBDAV_ACCOUNT : ${{ secrets.TEST_WEBDAV_ACCOUNT }}
        TEST_WEBDAV_PASSWORD : ${{ secrets.TEST_WEBDAV_PASSWORD }}
        TEST_WEBDAV_HOST : ${{ secrets.TEST_WEBDAV_HOST }}
        TEST_WEBDAV_PORT : ${{ secrets.TEST_WEBDAV_PORT }}
        TEST_WEBDAV_PATH : ${{ secrets.TEST_WEBDAV_PATH }}
      run: mvn -B package --file pom.xml
